### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by krsh123** [krsh123/DSA-CPP#19]
Add Seclection Sort program in the Sorting Algorithm folder.
Things to remember before making pull requests
- File name should be SelectionSort.c or SelectionSort.cpp
- File should be in the Sorting Algorithm folder.

**Comment by siddhesh-desai** [comment]
Hello @krsh123 Please assign it to me

**Comment by theshoonyam** [comment]
Please assign this issue to me.

**Comment by krsh123** [comment]
Selection Sort has added to Sorting Algorithm folder. Thank to @siddhesh-desai
